
export const state = () =>({
    artists:[
    {
        id:1,
        name:"D'angelo",
        country:"US",
        sex:"man",
        spotify:"https://open.spotify.com/embed/artist/336vr2M3Va0FjyvB55lJEd",
        label:"RCA/Virgin/EMI/JRecords",
        gender:true,
        us:true
    },
    {
        id:2,
        name:"Erykah Badu",
        country:"US",
        sex:"woman",
        spotify:"https://open.spotify.com/embed/artist/7IfculRW2WXyzNQ8djX8WX",
        label:"Motown/MCA/Universal",
        gender:false,
        us:true
    },
    {
        id:3,
        name:"Omar",
        country:"UK",
        sex:"man",
        spotify:"https://open.spotify.com/embed/artist/0BzTIDnFI4pvhy7vVNd41Z",
        label:"RCA/Talkin'Loud",
        gender:true,
        uk:true
    },
    {
        id:4,
        name:"Lalah Hathaway",
        country:"US",
        sex:"woman",
        spotify:"https://open.spotify.com/embed/artist/0uNEy4544VZq2KOl7BsLuo",
        label:"GRP/Stax/Virgin/Caroline",
        gender:false,
        us:true
    },
    {
        id:5,
        name:"Dwele",
        country:"US",
        sex:"man",
        spotify:"https://open.spotify.com/embed/artist/7u6LfVyYpEzMpHLL7jTyvU",
        label:"Virgin/Talkin'Loud",
        gender:true,
        us:true
    },
    {
        id:6,
        name:"Musiq Soulchild",
        country:"US",
        sex:"man",
        spotify:"https://open.spotify.com/embed/artist/3UVRliakQfa1pMWIsNuiZ8",
        label:"DefJam/Atlantic",
        gender:true,
        us:true
    },
    {
        id:7,
        name:"Bilal",
        country:"US",
        sex:"man",
        spotify:"https://open.spotify.com/embed/artist/4jCbgl5Dmt3uOh8WRQfpPs",
        label:"Interscope/Universal",
        gender:true,
        us:true
    },
    {
        id:8,
        name:"Angie Stone",
        country:"US",
        sex:"woman",
        spotify:"https://open.spotify.com/embed/artist/2hWr3AjjKOCVmWcwvuT4uM",
        label:"Stax/Arista/BMG/Jrecord//others...",
        gender:false,
        us:true
    },
    {
        id:9,
        name:"Maxwell",
        country:"US",
        sex:"man",
        spotify:"https://open.spotify.com/embed/artist/2AOt5htsbtyaHd5Eq3kl3j",
        label:"Columbia",
        gender:true,
        us:true
    },
    {
        id:10,
        name:"Rahsaan Patterson",
        country:"US",
        sex:"man",
        spotify:"https://open.spotify.com/embed/artist/5jVkC5rSgdK2EPfRAmtbpH",
        label:"MackAvenue/ArtistryMusic",
        gender:true,
        us:true
    },
    {
        id:11,
        name:"Ledisi",
        country:"US",
        sex:"woman",
        spotify:"https://open.spotify.com/embed/artist/60ciIY5MouLc2Y9n34DJdA",
        label:"Verve/TommyBoy",
        gender:false,
        us:true
    },
    {
        id:12,
        name:"Jill Scott",
        country:"US",
        sex:"woman",
        spotify:"https://open.spotify.com/embed/artist/6AVLthptCPhfrxlHadOBJD",
        label:"HiddenBeach/Atlantic/Warner",
        gender:false,
        us:true
    },
    {
        id:13,
        name:"Eric Benet",
        country:"US",
        sex:"man",
        spotify:"https://open.spotify.com/embed/artist/1kjO72M26jZkv0aaGxJaov",
        label:"EMI/Warner/Reprise",
        gender:true,
        us:true
    },
    {
        id:14,
        name:"Alicia Keys",
        country:"US",
        sex:"woman",
        spotify:"https://open.spotify.com/embed/artist/3DiDSECUqqY1AuBP8qtaIa",
        label:"Arista/Bmg/Columbia/others...",
        gender:false,
        us:true
    },
    {
        id:15,
        name:"India.Arie",
        country:"US",
        sex:"woman",
        spotify:"https://open.spotify.com/embed/artist/7Gf3LSwa5hh8Cjo60WhVjC",
        label:"Motown",
        gender:false,
        us:true
    },
    {
        id:16,
        name:"Lauryn Hill",
        country:"US",
        sex:"woman",
        spotify:"https://open.spotify.com/embed/artist/2Mu5NfyYm8n5iTomuKAEHl",
        label:"Columbia/Legacy",
        gender:false,
        us:true
    },
    {
        id:17,
        name:"Raheem DeVaughn",
        country:"US",
        sex:"man",
        spotify:"https://open.spotify.com/embed/artist/59NO6KX7wQCG7jGdtH1NtL",
        label:"Jive/Zomba/Fontana",
        gender:true,
        us:true
    },
    {
        id:18,
        name:"N'Dambi",
        country:"US",
        sex:"woman",
        spotify:"https://open.spotify.com/embed/artist/3Qq0yiyJZJu8L2PS5zpFVX",
        label:"Stax",
        gender:false,
        us:true
    },
    {
        id:19,
        name:"Jaheim",
        country:"US",
        sex:"man",
        spotify:"https://open.spotify.com/embed/artist/4sbB4Yy6Qig51pKCIKSLw3",
        label:"Atlantic/BMG/Warner",
        gender:true,
        us:true
    },
    {
        id:20,
        name:"Meshell Ndegeocello",
        country:"US",
        sex:"woman",
        spotify:"https://open.spotify.com/embed/artist/0uZRjholJ0fVC2J9EvnYnj",
        label:"Universal/Decca/warner/others...",
        gender:false,
        us:true
    },
    {
        id:21,
        name:"Toshinobu Kubota",
        country:"Japan",
        sex:"man",
        spotify:"https://open.spotify.com/embed/artist/45JvI0rkPkFFL14Cj0eput",
        label:"Sony",
        gender:true,
        other:true
    },
    ],
    
})
